In [6]:
%pip install sqlalchemy
%pip install pandas
%pip install numpy
%pip install psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\projects\finances_analysis\.venv\lib\site-packages (2.0.41)
Requirement already satisfied: greenlet>=1 in c:\projects\finances_analysis\.venv\lib\site-packages (from sqlalchemy) (3.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\projects\finances_analysis\.venv\lib\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\projects\finances_analysis\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\projects\finances_analysis\.venv\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\projects\finances_analysis\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\projects\finances_analysis\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\projects\finances_analysis\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\projects\finances_analysis\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\projects\finances_analysis\.venv\lib\site-packages (2.3.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: psycopg2-binary in c:\projects\finances_analysis\.venv\lib\site-packages (2.9.10)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import date

#### Read file

In [8]:
column_names = [
    'Accountnumber', 'Heading', 'Name', 'Currency', 'Statement number',
    'Date', 'Description', 'Value date', 'Amount', 'Balance',
    'Credit', 'Debit', 'Counterparty account number', 'Counterparty BIC',
    'Counterparty name', 'Counterparty address', 'Standard-format reference',
    'Free-format reference'
]

In [9]:
data = pd.read_csv(
    "data/00_zichtrekening.csv",
    sep=";",
    encoding="utf-8",
    usecols=range(18),
    names=column_names,
    skiprows=1,
    na_values=["NaN"],
    parse_dates=["Date"],
    dayfirst=True
)

In [10]:
# data.head()

####  Drop unnecessary columns

In [11]:
data.drop(['Heading', 'Name', 'Statement number', 'Value date', 'Counterparty BIC', 'Counterparty address', 'Credit', 'Debit'], axis=1, inplace=True)

####  Rename columns

In [12]:
data = data.rename(columns={
    'Accountnumber': 'account_number',
    'Currency': 'currency',
    'Date': 'date',
    'Description': 'description',
    'Amount': 'amount',
    'Balance': 'balance',
    'Counterparty account number': 'counterparty_account_number',
    'Counterparty name': 'counterparty_name',
    'Free-format reference': 'free_format_reference',
    'Standard-format reference': 'standard_format_reference'})

#### Assign correct types

In [13]:
for col in ['amount', 'balance']:
    data[col] = data[col].astype(str).str.replace(',', '.').replace('nan', None)
    data[col] = data[col].astype(float)

# Convert 'Date' to datetime
data['Date'] = pd.to_datetime(data['date'], errors='coerce')  # use errors='coerce' to avoid crashing on bad formats

#### Transform data

In [14]:
# For every row where both 'counterparty_account_number' and 'counterparty_name' are NaN, extract the 'counterparty_name' from the 'Description' column
mask = data['counterparty_name'].isna() & data['counterparty_account_number'].isna()
# Extract 'counterparty_name' from the Description column
extracted_names = data.loc[mask, 'description'].str.extract(r'(?:TIME|UUR)\s+(.*?)\s+(?:BE|NL|LUL|FR|DE|ES|PL|\d{4} IEDUBLIN)', expand=False)
# Assign the extracted names to the 'counterparty_name' column
data.loc[mask, 'counterparty_name'] = extracted_names

# For every row where descrition starts with "DEPOSIT"
mask_deposit = data['description'].str.startswith("DEPOSIT", na=False)
# Only set counterparty_name to "Bankautomaat" where it is NaN
data.loc[mask_deposit & data['counterparty_name'].isna(), 'counterparty_name'] = "Cash deposit"

# For every row where description starts with "AUTOMATIC SAVINGS"
mask_savings = data['description'].str.startswith("AUTOMATIC SAVINGS", na=False)
# Extract BE IBAN in the format "BE12 1234 4566 7890"
extracted_iban = data.loc[mask_savings, 'description'].str.extract(
    r'(BE\d{2}\s\d{4}\s\d{4}\s\d{4})', expand=False
)
# Assign extracted IBAN to counterparty_account_number
data.loc[mask_savings, 'counterparty_account_number'] = extracted_iban

mask_mobile = data['description'].str.startswith("MOBILE PAYMENT", na=False)
# counterparty_name instellen
data.loc[mask_mobile, 'counterparty_name'] = "Payconiq"

In [15]:
# data[data['counterparty_name'].isna()]
# data.head()

In [16]:
# Convert text columns
text_columns = ['account_number', 'currency', 'description', 'counterparty_account_number', 'counterparty_name', 'free_format_reference']
for col in text_columns:
    data[col] = data[col].astype(str)

#### Retrieve data and store them into DB

In [17]:
print(data.columns.tolist())

['account_number', 'currency', 'date', 'description', 'amount', 'balance', 'counterparty_account_number', 'counterparty_name', 'standard_format_reference', 'free_format_reference', 'Date']

In [18]:
# BUILD CONNECTION TO DB
engine = create_engine("postgresql://arthur:arthur@localhost:5432/finances_db")

In [19]:
# ACCOUNT TABLE
internal_accounts = pd.DataFrame([
    {'iban': 'BE76 7340 4232 9795', 'name': 'Zichtrekening', 'type': 'internal'},
    {'iban': 'BE31 7450 2762 4255', 'name': 'Spaarrekening', 'type': 'internal'},
    {'iban': 'BE98 7410 2384 6393', 'name': 'Start2Safe', 'type': 'internal'},
])

In [20]:
accounts = data[['counterparty_account_number', 'counterparty_name']].copy()
accounts.columns = ['iban', 'name']
accounts.drop_duplicates(subset=['iban', 'name'], inplace=True)
accounts.reset_index(drop=True, inplace=True)

In [21]:
# CATEGORY TABLE
categories = [
    ('ATM / Cash', 'expense', ''),
    ('Bars & Restaurants', 'expense', ''),
    ('Education', 'expense', ''),
    ('Finance & Insurances', 'expense', ''),
    ('Government', 'expense', ''),
    ('Entertainment', 'expense', ''),
    ('Mobility', 'expense', ''),
    ('Personal care', 'expense', ''),
    ('Services', 'expense', ''),
    ('Shopping', 'expense', ''),
    ('Utilities & Telecom', 'expense', ''),
    ('Housing', 'expense', ''),
    ('Other Expense', 'expense', ''),
    ('Salary', 'income', ''),
    ('Property', 'income', ''),
    ('Investment Income', 'income', ''),
    ('Other Income', 'income', ''),
    ('Savings', 'transfer', ''),
    ('Own Accounts', 'transfer', '')
]

# Create DataFrame
categories = pd.DataFrame(categories, columns=["name", "cashflow_type", "description"])

In [22]:
# FISCAL YEAR TABLE
start_year = 2020
current_year = date.today().year
end_year = current_year + 1

fiscal_years = pd.DataFrame({
    'year': range(start_year, end_year),
})
fiscal_years['start_date'] = pd.to_datetime(fiscal_years['year'].astype(str) + '-01-01')
fiscal_years['end_date'] = pd.to_datetime(fiscal_years['year'].astype(str) + '-12-31')

existing_years = pd.read_sql("SELECT year FROM fiscal_year", con=engine)
fiscal_years = fiscal_years[~fiscal_years['year'].isin(existing_years['year'])]

In [23]:
def is_new(row, existing):
    if pd.isna(row['iban']):
        # If IBAN is null, check only by name
        return not ((existing['name'] == row['name']) & existing['iban'].isna()).any()
    else:
        # Otherwise, check by both name and IBAN
        return not ((existing['name'] == row['name']) & (existing['iban'] == row['iban'])).any()

In [24]:
# INSERT into database

fiscal_years.to_sql(
    name='fiscal_year',
    con=engine,
    if_exists='append',
    index=False
)
print("Fiscal years inserted successfully.")

categories.to_sql(
    name='category',
    con=engine,
    if_exists='append',
    index=False
)
print("Categories inserted successfully.")

internal_accounts.to_sql(
    name='account',
    con=engine,
    if_exists='append',
    index=False
)
print("Internal accounts inserted successfully.")

existing_accounts = pd.read_sql("SELECT * FROM account", con=engine)
accounts_to_add = accounts[accounts.apply(is_new, axis=1, existing=existing_accounts)]
accounts_to_add.to_sql(
    name='account',
    con=engine,
    if_exists='append',  # or 'replace'
    index=False
)
print("Accounts inserted successfully.")

Fiscal years inserted successfully.
Categories inserted successfully.
Internal accounts inserted successfully.
Accounts inserted successfully.

In [25]:
# TRANSACTION TABLE
transactions = data[['account_number', 'counterparty_account_number', 'counterparty_name', 'date', 'amount', 'balance']].copy()
transactions.rename(columns={
    'account_number': 'account_id',
    'counterparty_account_number': 'counterparty_account_id',
}, inplace=True)
transactions['date'] = pd.to_datetime(transactions['date'], errors='coerce')

In [26]:
# FK relation to fiscal_year
fiscal_years = pd.read_sql("SELECT * FROM fiscal_year", con=engine)

# Ensure start_date and end_date are pandas Timestamps
fiscal_years['start_date'] = pd.to_datetime(fiscal_years['start_date'])
fiscal_years['end_date'] = pd.to_datetime(fiscal_years['end_date'])

def get_fiscal_id(date):
    fy = fiscal_years[(fiscal_years['start_date'] <= date) & (fiscal_years['end_date'] >= date)]
    return fy['fiscal_year_id'].iloc[0] if not fy.empty else None

transactions['fiscal_id'] = transactions['date'].apply(get_fiscal_id)

In [27]:
# FK relation to account
accounts = pd.read_sql("SELECT * FROM account", con=engine)

# Helper key: prefer IBAN if available, else name
accounts['account_key'] = accounts['iban'].fillna(accounts['name'])

def map_account(row, accounts_df, col_id, col_name):
    key = row[col_id] if pd.notna(row[col_id]) else row[col_name]
    match = accounts_df[accounts_df['account_key'] == key]
    return match['account_id'].iloc[0] if not match.empty else None

# Map main account using a merge (since it's always an IBAN)
transactions = transactions.merge(
    accounts[['account_id', 'iban']], 
    left_on='account_id',  # your transaction column with IBANs
    right_on='iban', 
    how='left'
)

transactions['account_id'] = transactions['account_id_y']

# Map counterparty account
transactions['counterparty_account_id'] = transactions.apply(
    lambda row: map_account(row, accounts, 'counterparty_account_id', 'counterparty_name'),
    axis=1
)

In [28]:
transactions = transactions[[
    'account_id', 
    'counterparty_account_id', 
    'date', 
    'amount', 
    'balance', 
    'fiscal_id'
]]

In [29]:
# INSERT into database

transactions.to_sql(
    'transaction',
    con=engine,
    if_exists='append',
    index=False
)
print("Transacties inserted successfully.")

Transacties inserted successfully.

#### Code in functions

In [30]:
accounts = pd.read_sql("SELECT * FROM account", con=engine)
fiscal_years = pd.read_sql("SELECT * FROM fiscal_year", con=engine)
categories = pd.read_sql("SELECT * FROM category", con=engine)
transactions = pd.read_sql("SELECT * FROM transaction", con=engine)

In [31]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           1021 non-null   int64
 1   account_id               1021 non-null   int64
 2   counterparty_account_id  1021 non-null   int64
 3   date                     1021 non-null   object
 4   amount                   1021 non-null   float64
 5   balance                  1021 non-null   float64
 6   fiscal_id                1021 non-null   int64
 7   description              0 non-null      object
dtypes: float64(2), int64(4), object(2)
memory usage: 63.9+ KB

In [32]:
transactions.groupby("fiscal_id").size().reset_index(name="count")

   fiscal_id  count
0          5    432
1          6    589

In [33]:
transactions.groupby("counterparty_account_id").size().reset_index(name="count")

    counterparty_account_id  count
0                         2     65
1                         3     15
2                         4    590
3                         5     48
4                         6      4
5                         7     44
6                         8     10
7                         9     20
8                        10     30
9                        11     25
10                       12     27
11                       13     23
12                       20      2
13                       22     42
14                       25      4
15                       26      6
16                       37      4
17                       38      2
18                       61      2
19                       68      2
20                       76      2
21                       80      2
22                       95     10
23                      100      2
24                      102      4
25                      115      8
26                      116      2
27                      140     18
28                      142      2
29                      153      2
30                      161      2
31                      165      2